/** What the documentation says of one error code. */
export interface ErrorDoc {
  /** What the code refuses, in a few words. */
  title: string;
  /** Why it is refused and what to write instead, where the message alone does not say. */
  detail?: string;
  /** The version that stopped raising it. A retired code stays listed and is never given out again. */
  retired?: string;
}

/** The areas codes are grouped in, by their first two digits, with the guide page that explains each. */
export const AREAS: Record<string, { name: string; guide?: string }> = {
  "00": { name: "Components and parsing" },
  "01": { name: "Script setup" },
  "02": { name: "Constants and enums" },
  "03": { name: "Props and types", guide: "props" },
  "04": { name: "Templates and attributes", guide: "generated_code" },
  "05": { name: "Child components", guide: "generated_code" },
  "06": { name: "Expressions" },
  "07": { name: "Strings and numbers", guide: "strings" },
  "08": { name: "Lists and loops", guide: "props" },
  "09": { name: "Slots", guide: "slots" },
  "10": { name: "Classes, styles and scoped styles", guide: "scoped_styles" },
  "11": { name: "Configuration and helpers", guide: "quick_start" },
  "12": { name: "Router", guide: "routing" },
  "13": { name: "Pinia stores", guide: "pinia" },
  "14": { name: "vue-i18n", guide: "i18n" },
  "15": { name: "Raw HTML, client-only content, teleports and Rust twins", guide: "errors_and_limits" },
  "16": { name: "Provide and inject", guide: "provide_inject" },
  "17": { name: "Page head", guide: "head" },
};

/** Every code the compiler raises. A code is never reused: one the compiler stops raising is marked
 * `retired` and stays listed. `pnpm errors:generate` writes the guide's index from this list. */
export const ERRORS = {
  FV0001: {
    title: "Source file that does not parse",
    detail: "A `<script setup>` block, or a file it reads, is not valid TypeScript. The message is the parser's own, with the line and column where it stopped.",
  },
  FV0002: { title: "Component file Vue cannot parse" },
  FV0003: { title: "`<script>` without `setup`" },
  FV0004: { title: "Component without a `<template>`" },
  FV0005: { title: "Template Vue cannot compile" },
  FV0006: {
    title: "Unexpected construct in Vue's compiled template",
    detail: "The compiler met output of Vue's server compiler that it has no translation for. Please report it with the component that caused it.",
  },
  FV0007: {
    title: "Component file name that gives no Rust module of its own",
    detail: "Each component is written to a Rust module named after its file in snake case (`UserCard.vue` is `user_card.rs`). A file name that is not letters, digits and `_` starting with a letter, two names with the same snake case (`FooBar.vue` and `Foo_bar.vue`), `Mod.vue`, and a name a module ferrovue writes for the project already has (`Types.vue`, `Stores.vue`) are refused.",
  },

  FV0101: { title: "`inheritAttrs` that is not `true` or `false`" },
  FV0102: { title: "`watch` with `immediate`" },
  FV0103: { title: "Effect that runs once on the server" },
  FV0104: { title: "`onServerPrefetch`" },
  FV0105: { title: "Statement in setup that could change what renders" },
  FV0106: { title: "`defineAsyncComponent` of anything but a component of this project" },
  FV0107: { title: "Unsupported statement in setup" },
  FV0108: { title: "`...rest` in destructured props" },
  FV0109: { title: "Destructured prop that is not a plain name" },

  FV0201: { title: "Constant that refers to itself" },
  FV0202: { title: "Enum member without a value after a string member" },
  FV0203: { title: "Enum member value that is not a string or number literal" },
  FV0204: { title: "Field a constant object does not have" },
  FV0205: { title: "Spread or hole in a constant list" },
  FV0206: { title: "Computed or spread key in a constant object" },
  FV0207: { title: "Constant that is not a literal" },
  FV0208: { title: "Constant object read whole" },
  FV0209: { title: "`null` in a constant list of plain values" },
  FV0210: { title: "Constant list of plain values of different types" },
  FV0211: { title: "Constant list mixing plain values and objects" },
  FV0212: { title: "Two constant lists with one Rust name" },
  FV0213: { title: "Object in a constant list without a required field" },
  FV0214: { title: "`null` for a field that is not nullable" },
  FV0215: { title: "Field of the wrong type in a constant list's object" },
  FV0216: { title: "Field of an unsupported type in a constant list's objects" },
  FV0217: { title: "Field that is only ever `null`" },
  FV0218: { title: "Field `null` in some objects and absent in others" },
  FV0219: { title: "Field of different types across a constant list's objects" },
  FV0220: { title: "Constant list's object type declared twice" },
  FV0221: { title: "Constant list's object type named as a Rust type" },
  FV0222: { title: "Constant object read by a key chosen at run time" },

  FV0301: { title: "`generic` that is not a list of type parameters" },
  FV0302: {
    title: "Type parameter without a constraint",
    detail: "A generic component renders each type parameter as its constraint, so `generic=\"T\"` alone gives the server no type. Write `generic=\"T extends string\"`.",
  },
  FV0303: { title: "Props declared at run time" },
  FV0304: { title: "Props type not declared in the component" },
  FV0305: { title: "`defineModel` without a type" },
  FV0306: { title: "`defineModel` of a nullable type that is not required" },
  FV0307: { title: "Default for a nullable prop" },
  FV0308: { title: "Unknown type" },
  FV0309: { title: "Type that is only `undefined`" },
  FV0310: { title: "Object type written in place" },
  FV0311: {
    title: "Type that may be both `null` and `undefined`",
    detail: "A Rust `Option` holds one kind of nothing, where JavaScript has two. Declare `T | null` or `x?: T`, never both. See [`props`](crate::guide::props#nullable-props).",
  },
  FV0312: { title: "Union of different types" },
  FV0313: { title: "`Record` not keyed by `string`" },
  FV0314: { title: "Type alias that refers to itself" },
  FV0315: { title: "Unsupported named type" },
  FV0316: { title: "Unsupported type" },
  FV0317: { title: "`Record` of unsupported values" },
  FV0318: { title: "Interface named as a Rust type" },
  FV0319: { title: "Type declared in two files" },
  FV0320: { title: "Interface with members other than plain named fields" },
  FV0321: { title: "Optional field of a nullable type" },
  FV0322: { title: "Prop default that is not a literal" },

  FV0401: { title: "Interpolation of a value that is not a string, a number or a boolean" },
  FV0402: { title: "Attribute value of an unsupported type" },
  FV0403: {
    title: "Attribute bound to a value Vue's server leaves out",
    detail: "Vue's server renderer leaves out an attribute bound to a list, an object or a `route.query` value, and hydration then sets it to the value's `String()` without reporting a mismatch. Join a list (`.join(\",\")`) or narrow a query value to one string.",
  },
  FV0404: { title: "Unsafe attribute name" },
  FV0405: {
    title: "Custom directive not listed in `clientDirectives`",
    detail: "A custom directive's `getSSRProps` may add attributes on the server, which ferrovue does not run. List a directive that adds none in `clientDirectives`.",
  },
  FV0406: { title: "`$attrs` on a root that takes scope ids" },
  FV0407: { title: "Attributes that are not an object literal" },
  FV0408: { title: "Computed or spread key in an attribute object" },
  FV0409: { title: "`className` bound in place of `class`" },
  FV0410: { title: "Merged attributes that are not object literals" },
  FV0411: { title: "Class merged with a string that may repeat the class before it" },
  FV0412: { title: "Fallthrough attribute of an unsupported type" },
  FV0413: { title: "`v-model` comparing values of types it cannot compare" },
  FV0414: { title: "`v-model` over an array" },
  FV0415: { title: "Value read from `$attrs`" },
  FV0416: { title: "Root `<Transition>` or `<KeepAlive>` around `v-if` that is given attributes" },
  FV0417: { title: "Attribute name chosen at run time" },
  FV0418: {
    title: "`<component :is>` over a value that is not a closed set",
    detail: "`<component :is>` compiles to a `match` over its choices, so each one must be known when compiling: an imported component, an HTML element's name, a `computed` or `?:` choosing among them, a prop typed as a union of string literals, or an object of imported components read by such a prop. A `string`, a `Component` or a value from elsewhere could be anything.",
  },
  FV0419: { title: "`<component :is>` naming something other than an HTML element" },
  FV0420: { title: "`<component :is>` over a prop that may be absent" },
  FV0421: { title: "`<component :is>` reading a key its object does not have" },
  FV0422: { title: "`v-html` or `v-text` on `<component :is>`" },
  FV0423: {
    title: "`v-show`, or `v-model` on `<select>`, in content rendered from virtual nodes",
    detail: "Inside an element `<component :is>` chooses, in the slot content such an element renders, and inside a `<RouterLink>`, Vue's server renders from virtual nodes, where `v-show` writes no `style` while it shows and `v-model` on a `<select>` marks no option `selected`. Bind `:style` or `:selected` yourself.",
  },

  FV0501: { title: "Child component that is not among the compiled components" },
  FV0502: { title: "Fallthrough attribute that would reach a child's prop" },
  FV0503: { title: "Child props that are not an object literal" },
  FV0504: { title: "Computed or spread key in child props" },
  FV0505: { title: "Attribute named by an integer" },
  FV0506: { title: "Required prop not passed" },
  FV0507: { title: "Required nullable prop not passed" },
  FV0508: { title: "Attributes passed to a child that takes none" },
  FV0509: { title: "String prop given a value that is not a string" },
  FV0510: { title: "One type declared separately by parent and child" },
  FV0511: { title: "Prop given a value of another type" },
  FV0512: { title: "`Props` imported from a component that is not compiled" },
  FV0513: { title: "Component resolved by name that is not imported" },

  FV0601: { title: "Name or function not available on the server" },
  FV0602: { title: "Unsupported method" },
  FV0603: { title: "Unsupported call" },
  FV0604: { title: "Field read on a value that is not an object" },
  FV0605: { title: "Field the type does not have" },
  FV0606: { title: "Value that may be absent where its target cannot take it as it is" },
  FV0607: { title: "Value of an unexpected type" },
  FV0608: { title: "`+` between unsupported types" },
  FV0609: { title: "Comparison between unsupported or absent values" },
  FV0610: { title: "Spread or hole in an array literal" },
  FV0611: { title: "Array literal of different types" },
  FV0612: { title: "Computed member access" },
  FV0613: { title: "Value set up in a way the server cannot evaluate" },
  FV0614: { title: "Logical operator between values that are not booleans" },
  FV0615: { title: "`??` falling back to a computed list" },
  FV0616: { title: "`??` between different types" },
  FV0617: { title: "`||` between unsupported types" },
  FV0618: { title: "Unsupported unary operator" },
  FV0619: { title: "`==` or `!=` with anything but `null` or `undefined`" },
  FV0620: { title: "Loose test against `undefined` of a value of a plugin's type" },
  FV0621: { title: "Comparison of a plugin's value with `null` or `undefined`" },
  FV0622: { title: "`===` between different types" },
  FV0623: { title: "Branches of `?:` of different types" },
  FV0624: { title: "`new` in an expression" },
  FV0625: { title: "Unsupported expression" },
  FV0626: { title: "Strict test of a value that may be `null` or `undefined`" },
  FV0627: { title: "Strict test against the absence a value cannot have" },

  FV0701: { title: "`Number()` of an unsupported value" },
  FV0702: { title: "`parseInt()` or `parseFloat()` of a value that is not a string" },
  FV0703: { title: "`parseInt()` with a radix other than a literal 10 or 16" },
  FV0704: { title: "Unsupported `Math` method" },
  FV0705: { title: "`.toFixed()` without a literal number of digits from 0 to 100" },
  FV0706: {
    title: "String that may hold half of a surrogate pair compared, searched or joined",
    detail: "`slice`, `substring`, `at`, `charAt` and `split(\"\")` can cut a surrogate pair in half. JavaScript keeps the half where ferrovue holds U+FFFD, so two such strings may compare, search or join differently. See [`strings`](crate::guide::strings#halves-of-surrogate-pairs).",
  },
  FV0707: { title: "`JSON.stringify()` of an unsupported value" },
  FV0708: { title: "Template literal of values that are not present strings, numbers or booleans" },
  FV0709: { title: "String method with the wrong number of arguments" },
  FV0710: { title: "Regular expression given to a string method" },
  FV0711: { title: "String method given a value that is not a present string" },
  FV0712: { title: "String method given a value that is not a present number" },
  FV0713: { title: "Function given to a string method" },
  FV0714: { title: "`.repeat()` by a negative or infinite count" },
  FV0715: { title: "Case mapping by the server's locale" },

  FV0801: { title: "`.includes()` of a value of another type than the list's" },
  FV0802: { title: "`.join()` with a separator that is not a string" },
  FV0803: { title: "List method on a value that is not a list" },
  FV0804: { title: "List method over a list of unsupported items" },
  FV0805: { title: "List method given anything but an arrow function" },
  FV0806: { title: "Arrow function with a block body" },
  FV0807: { title: "Arrow function index that is not a plain name" },
  FV0808: { title: "Defaults or nested patterns in an arrow function's item" },
  FV0809: { title: "Arrow function item bound by an unsupported pattern" },
  FV0810: { title: "`.map()` to optional or unsupported values" },
  FV0811: { title: "`.slice()` with more than two arguments" },
  FV0812: { title: "`.slice()` of values that are not numbers" },
  FV0813: { title: "List method given more than one function" },
  FV0814: { title: "`Object` method of a value that is not a `Record`" },
  FV0815: { title: "`Object.values()` of a record of lists" },
  FV0816: { title: "`Object.entries()` outside a `v-for`" },
  FV0817: { title: "Unsupported `Object` method" },
  FV0818: { title: "`v-for` over `Object.entries()` without `[key, value]`" },
  FV0819: { title: "`v-for` over an empty array literal" },
  FV0820: { title: "`v-for` over a value that is not a list or a number" },
  FV0821: { title: "Defaults or nested patterns in a `v-for` item" },
  FV0822: { title: "`v-for` item bound by an unsupported pattern" },
  FV0823: { title: "`v-for` key or index that is not a plain name" },

  FV0901: { title: "Slots that are not an object literal" },
  FV0902: { title: "Computed or spread slot name" },
  FV0903: { title: "Content for a slot the child does not have" },
  FV0904: { title: "Defaults or nested patterns in destructured slot props" },
  FV0905: { title: "Slot props bound by an unsupported pattern" },
  FV0906: { title: "Slot props taken from a slot that passes none" },
  FV0907: { title: "Slot read that the template does not render" },
  FV0908: { title: "Slot prop of a type with no Rust type" },
  FV0909: { title: "Array literal as a slot prop" },
  FV0910: { title: "Computed list as a slot prop" },
  FV0911: { title: "Slot prop of an unsupported type" },
  FV0912: { title: "Slot name that is not literal" },
  FV0913: { title: "Slot props that are not attributes or an object literal" },
  FV0914: { title: "Computed or spread key in slot props" },
  FV0915: { title: "Slot prop name that is not a plain name" },
  FV0916: { title: "Outlets of one slot that pass different props" },
  FV0917: { title: "Interface named as a slot's props type" },
  FV0918: { title: "Slot scope id given to content that takes none" },
  FV0919: {
    title: "`<slot>` with fallback content inside an element `<component :is>` chooses",
    detail: "Inside an element that `<component :is>` chooses, Vue renders a slot's content as virtual nodes and decides whether to show the fallback by rules of their own. Give the fallback from the parent instead.",
  },
  FV0920: { title: "`<slot>` rendered both inside and outside an element `<component :is>` chooses" },

  FV1001: { title: "Computed or spread key in a class object" },
  FV1002: { title: "Computed class name that is not a string" },
  FV1003: { title: "Class name with spaces around it" },
  FV1004: { title: "Class binding of an unsupported type" },
  FV1005: { title: "`<style module>`" },
  FV1006: { title: "`v-bind()` in CSS" },
  FV1007: { title: "Style binding of an unsupported type" },
  FV1008: { title: "Computed or spread key in a style object" },
  FV1009: { title: "Style property named by a number or starting with `:`" },
  FV1010: { title: "Style array mixing a string with objects" },
  FV1011: { title: "Style property whose place depends on a condition" },
  FV1012: { title: "Scope ids handed to a component whose render does not take them" },

  FV1101: { title: "Helper called with the wrong number of arguments" },
  FV1102: { title: "Configuration file not found" },
  FV1103: { title: "Configuration file that is not valid JSON" },
  FV1104: { title: "Configuration without `components` or `out`" },
  FV1105: { title: "Unsupported `scopeId`" },
  FV1106: { title: "`builders` that is not `true` or `false`" },
  FV1107: { title: "Unknown helper type" },
  FV1108: { title: "Imported function without a Rust twin" },
  FV1109: { title: "Twin name that is not PascalCase" },
  FV1110: { title: "Twin without `rust`" },
  FV1111: { title: "Twin prop name that is not camelCase" },
  FV1112: { title: "Twin slot name that is not a plain name" },

  FV1201: { title: "Route parameter that is not a present string or number" },
  FV1202: { title: "`to` that is not a string or an object literal" },
  FV1203: { title: "Computed or spread key in a `to` object" },
  FV1204: { title: "Unsupported key in a `to` object" },
  FV1205: { title: "`query` that is not an object literal" },
  FV1206: { title: "Computed or spread key in a query" },
  FV1207: { title: "Query value that may be `null`" },
  FV1208: { title: "`hash` that is not a string" },
  FV1209: { title: "Route name that is not a string literal" },
  FV1210: { title: "Unknown route name" },
  FV1211: { title: "`params` that is not an object literal" },
  FV1212: { title: "Computed or spread key in `params`" },
  FV1213: { title: "Unknown route parameter" },
  FV1214: { title: "Route parameter not given" },
  FV1215: { title: "`to` with both `path` and `params`" },
  FV1216: { title: "`path` that is not a string" },
  FV1217: { title: "`to` without `name` or `path`" },
  FV1218: { title: "`<RouterLink>` attributes that are not literal" },
  FV1219: { title: "Computed or spread key in `<RouterLink>` attributes" },
  FV1220: { title: "`custom` on `<RouterLink>`" },
  FV1221: { title: "`href` or `aria-current` set on `<RouterLink>`" },
  FV1222: { title: "`<RouterLink>` without `to`" },
  FV1223: { title: "Element in a `<RouterLink>` given a slot scope id" },
  FV1224: { title: "`<slot>` in a `<RouterLink>` that takes scope ids" },
  FV1225: { title: "`<RouterLink>` without `routes` configured" },
  FV1226: { title: "`<RouterLink>` attribute that is not a string literal" },
  FV1227: { title: "Fallthrough attribute that would reach a `<RouterLink>` prop" },
  FV1228: { title: "Fallthrough attribute that would replace a `<RouterLink>` attribute" },
  FV1229: { title: "`<RouterLink>` slot other than the default" },
  FV1230: { title: "Route read without `routes` configured" },
  FV1231: { title: "Route field not available on the server" },
  FV1232: { title: "Routes file that is not an array" },
  FV1233: { title: "Route entry of an unsupported shape" },
  FV1234: { title: "`typeof` of anything but a query value" },
  FV1235: { title: "`??` after a query value with a fallback that is not a string" },
  FV1236: { title: "`<RouterView>` in a component with `<style scoped>`" },
  FV1237: { title: "`<RouterView>` in a child component" },
  FV1238: { title: "`routes` that is neither a routes file nor `{ pages }`" },
  FV1239: { title: "Pages folder that cannot be read" },
  FV1240: {
    title: "Page file name the router cannot match",
    detail: "Each part of a page's path is plain text (letters, digits, `-` and `_`) or one whole parameter: `[id]`, `[[id]]` (optional) or `[...path]` (a catch-all, last). A parameter beside text in one part (`prefix-[id].vue`), a repeatable parameter (`[id]+`), an optional catch-all (`[[...path]]`), a parameter parser (`[id=int]`) and a character code (`[x+2E]`) are not matched on the server.",
  },
  FV1241: { title: "Named view in a page file name" },
  FV1242: {
    title: "`definePage()` in a page",
    detail: "`definePage()` changes a page's route (its name, path, alias, meta or params) at build time. ferrovue builds the server's routes from the files' paths alone, so the two would disagree.",
  },
  FV1243: { title: "`<route>` block in a page" },
  FV1244: { title: "`_parent.vue` with no pages to hold" },
  FV1245: { title: "Page whose component name is taken or not a Rust name" },

  FV1301: { title: "Type declared by two stores" },
  FV1302: { title: "Store id that is not a string literal" },
  FV1303: { title: "Store of an unsupported shape" },
  FV1304: { title: "Store `state` without a declared return type" },
  FV1305: { title: "Store `getters` that is not an object literal" },
  FV1306: { title: "Getter that is not a function of the state" },
  FV1307: { title: "Setup store without a block body" },
  FV1308: { title: "Unsupported statement in a setup store" },
  FV1309: { title: "Setup store that does not return an object" },
  FV1310: { title: "Setup store returning anything but plain names" },
  FV1311: { title: "Setup store returning a name it does not declare" },
  FV1312: { title: "Interface named as a setup store's state type" },
  FV1313: { title: "`ref<T | null>()` without a value" },
  FV1314: { title: "Setup store `ref` without a type" },
  FV1315: { title: "Getter with a block body" },
  FV1316: { title: "Getter that reads `this`" },
  FV1317: { title: "Getter that returns a function" },
  FV1318: { title: "Getters that read each other" },
  FV1319: { title: "Store imported by anything but its `use…` hook" },
  FV1320: { title: "`storeToRefs` of anything but a store bound in setup" },
  FV1321: { title: "`storeToRefs` not destructured into plain names" },
  FV1322: { title: "Store hook called with arguments" },

  FV1401: { title: "Locale file that is not valid JSON" },
  FV1402: { title: "Locale message that does not parse" },
  FV1403: { title: "Linked message with a key chosen at run time" },
  FV1404: { title: "Linked message with an unknown modifier" },
  FV1405: { title: "Locale message construct ferrovue does not render" },
  FV1406: { title: "`t()` value that is not a present string, number or boolean" },
  FV1407: { title: "`t()` without `i18n` configured" },
  FV1408: { title: "`t()` with unsupported arguments" },
  FV1409: { title: "`t()` key that is not a string" },
  FV1410: { title: "Computed or spread key in `t()`'s named values" },
  FV1411: { title: "Default message given to `t()`" },
  FV1412: { title: "Plural number that is not an integer" },
  FV1413: { title: "`useI18n()` not destructured into plain names" },

  FV1501: { title: "Twin props that are not attributes or an object literal" },
  FV1502: {
    title: "`v-html` of anything but a `TrustedHtml` prop",
    detail: "`v-html` writes raw HTML, which ferrovue allows only from a type you mark as trusted. See [`escaping`](crate::guide::escaping).",
  },
  FV1503: { title: "`TrustedHtml` prop without `trustedHtml` configured" },
  FV1504: { title: "Attributes on `<ClientOnly>`" },
  FV1505: { title: "`<ClientOnly>` slot other than the default and `#fallback`" },
  FV1506: { title: "Slot props taken from `<ClientOnly>`'s `#fallback`" },
  FV1507: { title: "`<Teleport>` in slot content whose emptiness is decided at run time" },
  FV1508: { title: "`<Teleport>` target that is not a string" },
  FV1509: { title: "Twin prop of a type with no Rust type" },
  FV1510: { title: "Twin for a component ferrovue compiles" },
  FV1511: {
    title: "`<ClientOnly>` with a `#fallback` in content rendered from virtual nodes",
    detail: "Inside an element `<component :is>` chooses, inside a `<RouterLink>` or a twin's slot, and in the slot content they render, Vue's server renders from virtual nodes, and `<ClientOnly>` writes an empty fragment there instead of its fallback, which the client then renders and reports as a mismatch. Leave out the `#fallback`, or move the `<ClientOnly>` outside that content.",
  },
  FV1512: {
    title: "`v-html` on an element whose content the browser rebuilds",
    detail: "The browser's HTML parser moves markup written in a `<table>`, `<thead>`, `<tbody>`, `<tfoot>`, `<tr>` or `<colgroup>` out of the table, drops the tags written in a `<select>` or `<optgroup>`, and ends SVG or MathML at an HTML tag, so the page holds other nodes than the server wrote and hydration mismatches. Put `v-html` on a `<td>`, `<th>` or `<caption>`, write the options in the template, or use an HTML element inside a `<foreignObject>` or an `<mtext>`. See [`escaping`](crate::guide::escaping).",
  },
  FV1513: {
    title: "`v-html` in a `<p>` of HTML that may hold blocks",
    detail: "A block tag in the HTML (`<p>`, `<ul>`, `<div>`) ends the `<p>` it is written in where the browser reads it. Type the prop `InlineHtml` from `ferrovue/types`, which is `ferrovue::InlineHtml` on the server and keeps only inline tags, or put the HTML in a `<div>`. Slot content placed into a child's `<p>` is not seen at compile time. See [`escaping`](crate::guide::escaping).",
  },

  FV1601: { title: "Injection key that is not a string literal or a symbol exported from a `.ts` file" },
  FV1602: { title: "Injection key symbol without an `InjectionKey<T>` type" },
  FV1603: { title: "`provide` or `inject` with unsupported arguments" },
  FV1604: { title: "`inject` that is not bound to a name at the top of `<script setup>`" },
  FV1605: { title: "`inject(key)!`, asserting a provider" },
  FV1606: { title: "`inject` of a string key with neither a default nor a type argument" },
  FV1607: { title: "Function default without the factory flag" },
  FV1608: { title: "Values of different types provided under one key" },
  FV1609: { title: "Provided value that may be `null` or `undefined`" },
  FV1610: { title: "Provided value of a form the context does not hold" },
  FV1611: { title: "Object provided or given as a default under a key without an interface type" },
  FV1612: { title: "Provided or default object whose fields do not match its interface" },
  FV1613: { title: "Ref and plain value under one key" },
  FV1614: { title: "Key provided twice by one component" },
  FV1615: { title: "Two keys that give the context one field name" },
  FV1616: {
    title: "`provide` in a component that holds `<RouterView>`",
    detail: "The page `<RouterView>` shows is rendered from Rust and handed in as a slot, so it cannot see what the component provides. Provide the value above the router (in Rust, through the `Provides` the page is rendered with) or below it.",
  },
  FV1617: {
    title: "String-keyed `inject` inside a Rust twin's slot",
    detail: "Content in a twin's slot is a child of the library component the twin stands for, which may provide the same string key on the client. Use an `InjectionKey` symbol, which only the project provides.",
  },
  FV1618: { title: "Setup that assigns to an injected value" },
  FV1619: { title: "Function and value provided under one key" },
  FV1620: { title: "`provide` or `inject` called inside an expression" },

  FV1701: { title: "Options given to `useHead`" },
  FV1702: { title: "Head input that is not an object literal" },
  FV1703: { title: "Head key ferrovue does not translate" },
  FV1704: { title: "Spread, computed key, hole or method in a head input" },
  FV1705: {
    title: "Function in a head input",
    detail: "unhead calls a function given as a value on the server only when it takes no arguments, as a getter (`title: () => props.title`), which ferrovue evaluates. A `titleTemplate` function and an event handler (`onload`) run with arguments or on the client.",
  },
  FV1706: { title: "Head value of a type the head does not take" },
  FV1707: { title: "`tagPosition`, `tagPriority` or `tagDuplicateStrategy` that is not a literal it accepts" },
  FV1708: { title: "`useHeadSafe`" },
  FV1709: { title: "`useSeoMeta` key or value ferrovue does not translate" },
  FV1710: {
    title: "`class` or `style` in the head that may be `null`",
    detail: "unhead's server renderer throws on a `class` or `style` of `null`. Write `?? undefined`, which leaves the attribute out.",
  },
  FV1711: { title: "`innerHTML` or `textContent` on a head tag that has no content" },
} as const satisfies Record<`FV${number}`, ErrorDoc>;

/** A stable error code, as `FV0604`. */
export type Code = keyof typeof ERRORS;

/** Where a code is documented. */
export function docsUrl(code: string): string {
  return `https://docs.rs/ferrovue/latest/ferrovue/guide/error_codes/index.html#${code.toLowerCase()}`;
}
