[package]
name = "ferrovue-example-greeting"
description = "A Rust program rendering Vue components compiled by ferrovue"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
ferrovue.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
